[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-cognitiveservices-speech>=1.51.2",
    "fastapi>=0.139.2",
    "faster-whisper>=1.2.1",
    "fugashi>=1.5.2",
    "groq>=1.7.0",
    "ipython>=9.16.1",
    "kokoro>=0.9.4",
    "livekit>=1.1.13",
    "livekit-agents[silero]~=1.5",
    "livekit-api>=1.2.0",
    "misaki[ja]>=0.9.4",
    "ollama>=0.6.2",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "scipy>=1.18.0",
    "silero-vad>=6.2.1",
    "soundfile>=0.14.0",
    "torch>=2.13.0",
    "unidic>=1.1.0",
    "uvicorn[standard]>=0.51.0",
]

