spring.application.name=saas_japan

# config data
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://saas-japanese-db-saas-japanese.h.aivencloud.com:25142/saas_japan?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password={xxxx}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# api key mail service
brevo.api.key={xxxx}

# jwt rsa
jwt.private-key=classpath:certs/private.pem
jwt.public-key=classpath:certs/public.pem

#cloudinary
cloudinary.cloud-name={xxxx}
cloudinary.api-key={xxxx}
cloudinary.api-secret={xxxx}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

sepay.merchant-id={xxxx}
sepay.secret-key={xxxx}
sepay.checkout-url={xxxx}