spring.application.name=saas_japanese

#config data
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/saas_japan
spring.datasource.username=root
spring.datasource.password=160304
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true

# api key mail service
brevo.api.key=xxxx

# jwt rsa
jwt.private-key=classpath:certs/private.pem
jwt.public-key=classpath:certs/public.pem

#cloudinary
cloudinary.cloud-name=xxxx
cloudinary.api-key=xxxx
cloudinary.api-secret=xxxx
