spring.application.name=saas_japan

# config data
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

# api key mail service
brevo.api.key=${BREVO}

# jwt rsa
jwt.private-key=classpath:certs/private.pem
jwt.public-key=classpath:certs/public.pem

#cloudinary
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_KEY}
cloudinary.api-secret=${CLOUD_SECRET}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

sepay.merchant-id=${SEPAY_ID}
sepay.secret-key=${SEPAY_KEY}
sepay.checkout-url=${SEPAY_URL}
